= Modular {VertX} Guide
:VertX: Vert.x
:v5: 5
:v5x: 5.x
:VertX5: Vert.x 5

Starting {v5}, {VertX} supports building modular applications and services with the {VertX} stack.

This document aims to guide the developer toward building and running a modular applications with {VertX}.

== Definitions

We borrow terminology from this https://github.com/tfesenko/Java-Modules-JPMS-CheatSheet/blob/master/README.md#types-of-modules-named-and-unnamed[document] for the following names:

- _named_ module
- _explicit_ module
- _automatic_ module

== Maturity model

{VertX} strives to deliver the most mature JPMS level support (see https://nipafx.dev/java-modules-jpms-maturity-model/).

Most {VertX} components support level 3 (according to the maturity model) and explicit modules, however a few modules have been left aside, due to constraints preventing proper modularity to happen, often due to a faulty dependency, e.g. a split package.

== Native transports

Native transports are supported.

The module `io.netty.transport.classes.${native.detected.transport}` is required as it contains the transport classes.

The module `io.netty.transport.${native.transport}.${os.name}.${os.detected.arch}` contains the native library and its presence is only required at runtime.

You can add them to the JVM launch command with `--add-modules --add-modules io.netty.transport.classes.${native.transport},io.netty.transport.${native.transport}.${os.detected.name}.${os.detected.arch}`.

Alternatively you can also add them to your module descriptor (even though your application does not use them) which usually triggers tools to add them automatically at runtime, however this binds your module to a specific os/architecture:

[source,java]
----
// Add to module-info.java
requires io.netty.transport.classes.kqueue;
requires io.netty.transport.kqueue.osx.aarch_64;
----

You can find an https://github.com/vert-x3/vertx-examples/tree/5.x/jpms-examples#native-transports[example with OpenSSL] among {VertX} JPMS examples.

== OpenSSL

OpenSSL is supported.

The module `io.netty.tcnative.classes.openssl` is required as it contains the OpenSSL Netty classes.

The module `io.netty.internal.tcnative.openssl.${os.detected.name}.${os.detected.arch}` contains the native library and its presence is only required at runtime.

You can add them to the JVM launch command with `--add-modules io.netty.transport.classes.${native.transport},io.netty.transport.${native.transport}.${os.detected.name}.${os.detected.arch}`.

Alternatively you can also add them to your module descriptor (even though your application does not use them) which usually triggers tools to add them automatically at runtime, however this binds your module to a specific os/architecture:

[source,java]
----
// Add to your module-info.java
requires io.netty.tcnative.classes.openssl;
requires io.netty.internal.tcnative.openssl.osx.aarch_64;
----

You can find an https://github.com/vert-x3/vertx-examples/tree/5.x/jpms-examples#open-ssl[example with OpenSSL] among {VertX} JPMS examples.

== HTTP Compression

{VertX} supports _gzip_ and _deflate_ algorithms out of the box, however _brotli_ and _zstd_ algorithms requires you to respectively add the following dependencies:

- Brotli: `com.aayushatharva.brotli4j:brotli4j`
- Zstd: `com.github.luben:zstd-jni`

These dependencies are optional since not everyone need them and when used, they are required at runtime instead of compile time.

You can add them to the JVM launch command with `--add-modules com.aayushatharva.brotli4j,com.github.luben.zstd_jni`.

Alternatively you can also add them to your module descriptor (even though your application does not use them) which usually triggers tools to add them automatically at runtime.

[source,java]
----
// Add to your module-info.java
requires com.aayushatharva.brotli4j;
requires com.github.luben.zstd_jni;
----

You can find an https://github.com/vert-x3/vertx-examples/tree/5.x/jpms-examples#http-compression[example with Brotli] among {VertX} JPMS examples.

== Code generation

Code generation of a modular application is supported.

The following module are available for applications:

|===
|Artifact ID|Module name|Description
|_vertx-codegen-api_
|`io.vertx.codegen.api`
|Codegen annotations, e.g. `io.vertx.codegen.annotations.DataObject`
|_vertx-codegen-json_
|`io.vertx.codegen.json`
|JSON generator API, e.g. `io.vertx.codegen.json.JsonGen`
|===

Your application requires these components on the module path.

The {VertX} 4 `vertx-codegen` component has been split between

- `vertx-codegen-processor` contains the annotation processor only necessary to the Java compiler
- `vertx-codegen-api` contains the annotations
- `vertx-codegen-json` contains the json generator

`vertx-codegen` still exists for backward compatibility purpose, feel free to use it or use finer grained dependencies.

=== Service proxy generation

Here is the bare minimum required by your module to generate a service proxy.

[source,java]
----
// Service proxy
requires static io.vertx.codegen.api;
requires static io.vertx.codegen.json;
----

You can find the https://github.com/vert-x3/vertx-examples/tree/5.x/jpms-examples#service-proxy[service proxy example] among our set of examples.

=== Sql Client Template generation

Here is the bare minimum required by your module to generate a Sql Client Template.

[source,java]
----
requires static io.vertx.codegen.api;
requires io.vertx.sql.client;
requires io.vertx.sql.client.templates;
----

You can find the https://github.com/vert-x3/vertx-examples/tree/5.x/jpms-examples#sql-client-template[Sql Client Template] among our set of examples.

== Components

=== Core

|===
|Artifact ID| Module name|Dependencies

|_vertx-core_
|`io.vertx.core`
|explicit

|_vertx-core-logging_
|`io.vertx.core.logging`
|explicit
|===

CAUTION: Your application should never require `io.vertx.core.logging`, this module contains the logging abstraction used by {VertX} for logging purposes and is exclusively used by {VertX} components. Your application should use the logging framework of your choice and configure {VertX} logging to use it.

==== Dependencies

Transitive dependencies are explicit modules.

- The Netty library `io.netty:*` (See https://github.com/netty/netty/blob/4.2/testsuite-jpms/README.md[Modular Netty])
- The Jackson library `com.fasterxml.jackson.core:*`
- Apache Log4j 2 `org.apache.logging.log4j:*`
- SLF4J `org.slf4j:*`

Optional dependencies are explicit modules.

- Brotli4j `com.aayushatharva.brotli4j:brotli4j`
- Zstd-jni `com.github.luben:zstd-jni`

=== Auth

|===
|Artifact ID| Module name|Dependencies

|_vertx-auth-common_
|`io.vertx.auth.common`
|explicit

|_vertx-auth-htpasswd_
|`io.vertx.auth.htpasswd`
|explicit

|_vertx-auth-abac_
|`io.vertx.auth.abac`
|explicit

|_vertx-auth-ldap_
|`io.vertx.auth.ldap`
|explicit

|_vertx-auth-sqlclient_
|`io.vertx.auth.sqlclient`
|explicit

|_vertx-auth-oauth2_
|`io.vertx.auth.oauth2`
|explicit

|_vertx-auth-htdigest_
|`io.vertx.auth.htdigest`
|explicit

|_vertx-auth-jwt_
|`io.vertx.auth.jwt`
|explicit

|_vertx-auth-properties_
|`io.vertx.auth.properties`
|explicit

|_vertx-auth-webauthn4j_
|`io.vertx.auth.webauthn4j`
|explicit

|_vertx-core-otp_
|`io.vertx.core.otp`
|explicit
|===

==== Dependencies

Transitive dependencies are explicit modules.

=== Service Resolver

|===
|Artifact ID| Module name|Dependencies
|_vertx-service-resolver_
|`io.vertx.serviceresolver`
|explicit
|===

=== URI templates

|===
|Artifact ID| Module name|Dependencies
|_vertx-uri-template_
|`io.vertx.uritemplate`
|explicit
|===

=== Web

|===
|Artifact ID| Module name|Dependencies

|_vertx-web-common_
|`io.vertx.web.common`
|explicit

|_vertx-web_
|`io.vertx.web`
|explicit

|_vertx-web-openapi-router_
|`io.vertx.web.openapi-router`
|explicit

|_vertx-web-validation_
|`io.vertx.web.validation`
|explicit

|_vertx-web-proxy_
|`io.vertx.web.proxy`
|explicit

|_vertx-web-graphql_
|`io.vertx.web.graphql`
|automatic

|_vertx-web-client_
|`io.vertx.web.client`
|explicit

|_vertx-web-sstore-redis_
|`io.vertx.web.sstore.redis`
|explicit

|_vertx-web-sstore-cookie_
|`io.vertx.web.sstore.cookie`
|explicit

|_vertx-web-api-service_
|`io.vertx.web.apiservice`
|explicit

|_vertx-web-template-mvel_
|`io.vertx.web.template.mvel`
|automatic

|_vertx-web-template-freemarker_
|`io.vertx.web.template.freemarker`
|automatic

|_vertx-web-template-thymeleaf_
|`io.vertx.web.template.thymeleaf`
|automatic

|_vertx-web-template-rocker_
|`io.vertx.web.template.rocker`
|automatic

|_vertx-web-template-handlebars_
|`io.vertx.web.template.handlebars`
|automatic

|_vertx-web-template-jte_
|`io.vertx.web.template.jte`
|automatic
|===

The following template engine do not support modularity at the moment:

- _vertx-web-template-httl_
- _vertx-web-template-pebble_
- _vertx-web-template-pug_
- _vertx-web-template-rythm_

=== SQL Client

|===
|Artifact ID| Module name|Dependencies
|_vertx-sql-client_
|`io.vertx.sql.client`
|explicit
|_vertx-pg-client_
|`io.vertx.sql.client.pg`
|explicit
|_vertx-mssql-client_
|`io.vertx.sql.client.mssql`
|explicit
|_vertx-mysql-client_
|`io.vertx.sql.client.mysql`
|explicit
|_vertx-pg-client_
|`io.vertx.sql.client.pg`
|explicit
|_vertx-oracle-client_
|`io.vertx.sql.client.oracle`
|automatic
|_vertx-jdbc-client_
|`io.vertx.sql.client.jdbc`
|depends on the JDBC library
|===

=== Redis Client

|===
|Artifact ID| Module name|Dependencies
|_vertx-redis-client_
|`io.vertx.redisclient`
|explicit
|===

=== Mail Client

|===
|Artifact ID| Module name|Dependencies
|_vertx-mail-client_
|`io.vertx.mail.client`
|explicit
|===

=== Cassandra Client

|===
|Artifact ID| Module name|Dependencies
|_vertx-cassandra-client_
|`io.vertx.client.cassandra`
|automatic
|===

=== Consul Client

|===
|Artifact ID| Module name|Dependencies
|_vertx-consul-client_
|`io.vertx.consul.client`
|explicit
|===

=== Amqp Client

|===
|Artifact ID| Module name|Dependencies
|_vertx-amqp-client_
|`io.vertx.amqpclient`
|explicit
|===

=== Mongo Client

|===
|Artifact ID| Module name|Dependencies
|_vertx-mongo-client_
|`io.vertx.mongo.client`
|automatic
|===

=== Stomp

|===
|Artifact ID| Module name|Dependencies
|_vertx-stomp_
|`io.vertx.stomp`
|explicit
|===

=== Circuit Breaker

|===
|Artifact ID| Module name|Dependencies
|_vertx-circuit-breaker_
|`io.vertx.circuitbreaker`
|explicit
|===

=== Health checks

|===
|Artifact ID| Module name|Dependencies
|_vertx-health-checks_
|`io.vertx.healtcheck`
|explicit
|===

=== Config

|===
|Artifact ID| Module name|Dependencies
|_vertx-config_
|`io.vertx.config`
|explicit

|_vertx-config-git_
|`io.vertx.config.git`
|automatic

|_vertx-config-hocon_
|`io.vertx.config.hocon`
|automatic

|_vertx-config-configmap_
|`io.vertx.config.configmap`
|explicit

|_vertx-config-spring_
|`io.vertx.config.spring`
|explicit

|_vertx-config-yaml_
|`io.vertx.config.yaml`
|explicit

|_vertx-config-consul_
|`io.vertx.config.consul`
|explicit

|_vertx-config-redis_
|`io.vertx.config.redis`
|explicit
|===

=== Json Schema

|===
|Artifact ID| Module name|Dependencies
|_vertx-json-schema_
|`io.vertx.jsonschema`
|explicit
|===

=== Open API

|===
|Artifact ID| Module name|Dependencies
|_vertx-open-api_
|`io.vertx.openapi`
|explicit
|===

=== MQTT

|===
|Artifact ID| Module name|Dependencies
|_vertx-mqtt_
|`io.vertx.mqtt`
|explicit
|===

=== gRPC

|===
|Artifact ID| Module name|Dependencies
|_vertx-grpc-common_
|`io.vertx.grpc.common`
|automatic
|_vertx-grpc-client_
|`io.vertx.grpc.client`
|automatic
|_vertx-grpc-server_
|`io.vertx.grpc.server`
|automatic
|===

The following modules do not support modularity:

- _vertx-grpcio-common_
- _vertx-grpcio-client_
- _vertx-grpcio-server_

Since {VertX5}, the {Vertx} gRPC stack is split in two

- `vertx-grpc-\*` artifacts providing explicit modules, yet relying on `com.google.protobuf` and `com.google.protobuf.util` named automatic modules
- `vertx-grpc-io-\*` artifacts which cannot be modular, relying on the non-modular `io.grpc:*` artifacts

Concerning the `com.google.protobuf.*` artifacts, there is a modular version of it in the https://github.com/elide-dev/jpms[JPMS Attic Repository] until
the Java Protocol Buffers library supports it. Here is an https://github.com/vert-x3/vertx-examples/tree/5.x/jpms-examples#grpc-service[example] of a modular gRPC service.

=== JUnit 5

|===
|Artifact ID| Module name|Dependencies
|_vertx-junit5_
|`io.vertx.testing.junit5`
|explicit
|===

{VertX} examples provide a few simple tests https://github.com/vert-x3/vertx-examples/tree/5.x/jpms-examples/src/test/java/io/vertx/example/jpms/tests[examples] written with JUnit 5.

=== Metrics

==== Micrometer Metrics

|===
|Artifact ID| Module name|Dependencies
|_vertx-micrometer-metrics_
|`io.vertx.metrics.micrometer`
|automatic
|===

{VertX} Micrometer Metrics supports different backend registries.
It requires you to add one of the following dependencies:

- Prometheus: `io.micrometer:micrometer-registry-prometheus`
- InfluxDB: `io.micrometer:micrometer-registry-influx`
- JMX: `io.micrometer:micrometer-registry-jmx`
- Graphite: `io.micrometer:micrometer-registry-graphite`

These dependencies are optional since not everyone need them and when used, they are required at runtime instead of compile time.

You can add them to the JVM launch command with:

- Prometheus: `--add-modules micrometer.registry.prometheus,io.prometheus.metrics.model`
- InfluxDB: `--add-modules micrometer.registry.influx`
- JMX: `--add-modules micrometer.registry.jmx`
- Graphite: `--add-modules micrometer.registry.graphite`

Alternatively you can also add them to your module descriptor (even though your application does not use them) which usually triggers tools to add them automatically at runtime.

[source,java]
----
// Add to your module-info.java
requires micrometer.registry.prometheus;
requires io.prometheus.metrics.model;
requires micrometer.registry.influx;
requires micrometer.registry.jmx;
requires micrometer.registry.graphite;
----

==== Dropwizard Metrics

|===
|Artifact ID| Module name|Dependencies
|_vertx-dropwizard-metrics_
|`io.vertx.metrics.dropwizard`
|automatic
|===

=== Tracing

==== Zipkin Tracing

|===
|Artifact ID| Module name|Dependencies
|_vertx-zipkin_
|`io.vertx.tracing.zipkin`
|automatic
|===

==== Open Telemetry Tracing

|===
|Artifact ID| Module name|Dependencies
|_vertx-opentelemetry_
|`io.vertx.tracing.opentelemetry`
|automatic
|===

==== Clustering

==== Hazelcast Clustering

|===
|Artifact ID| Module name|Dependencies
|_vertx-hazelcast_
|`io.vertx.clustermanager.hazelcast`
|explicit
|===

NOTE: multicast join is not supported on the module path on macOS, instead Hazelcast TCP configuration is required

=== HTTP Proxy

|===
|Artifact ID| Module name|Dependencies
|_vertx-http-proxy_
|`io.vertx.httpproxy`
|explicit
|===
